apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: <NAME>
spec:
  maxReplicas: 40
  minReplicas: 1
  targetCPUUtilizationPercentage: 70
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: <DEPLOYMENT_NAME>