apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-envoy
data:
  envoy.json: |
    {
      "admin": {
        "access_log_path": "/dev/stdout",
        "address": "tcp://127.0.0.1:8001"
      },
      "static_resources": {
        "listeners": [
          {
            "address": "tcp://0.0.0.0:8080",
          }
        ],
        "clusters": [
          {
            "name": "backend",
            "type": "static",
            "lb_policy": "ROUND_ROBIN",
            "hosts": [
              {
                "socket_address": {
                  "address": "127.0.0.1",
                  "port_value": 50001
                }
              }
            ]
          }
        ]
      }
    }