apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: server
          image: local/gateway:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 50002
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:50002"]
            initialDelaySeconds: 5
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:50002"]
            initialDelaySeconds: 10
          env:
            - name: BACKEND_PORT
              value: "backend:50001"
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - name: "grpc"
      protocol: "TCP"
      port: 8080
      nodePort: 31000
      targetPort: 50002