apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      volumes:
        - name: envoy-config
          configMap:
            name: gateway-envoy
      containers:
        - name: envoy
          image: envoyproxy/envoy:latest
          command:
            - "/usr/local/bin/envoy"
          args:
            - "--config-path /etc/envoy/envoy.yaml"
          resources:
            limits:
              memory: 512Mi
          volumeMounts:
            - name: envoy-config
              mountPath: /etc/envoy
          ports:
            - containerPort: 8080
              name: app
            - containerPort: 8001
              name: envoy-admin
        - name: server
          image: gcr.io/my-first-project-236315/grpc-test/gateway
          ports:
            - containerPort: 50002
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:50002"]
            initialDelaySeconds: 5
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:50002"]
            initialDelaySeconds: 10
          env:
            - name: BACKEND_PORT
              value: "localhost:50001"
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: LoadBalancer
  selector:
    app: gateway
  ports:
    - name: "grpc"
      protocol: "TCP"
      port: 10000
      nodePort: 31000
      targetPort: 10000