apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      volumes:
        - name: envoy
          configMap:
            name: backend-envoy
      containers:
        - name: envoy
          image: envoyproxy/envoy:latest
          command:
            - "/usr/local/bin/envoy"
          args:
            - "--config-path /etc/envoy/envoy.json"
          resources:
            limits:
              memory: 512Mi
          volumeMounts:
            - name: envoy
              mountPath: /etc/envoy
          ports:
            - containerPort: 8080
              name: app
            - containerPort: 8001
              name: envoy-admin
        - name: server
          image: gcr.io/my-first-project-236315/grpc-test/backend
          ports:
            - containerPort: 50001
          env:
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:50001"]
            initialDelaySeconds: 5
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:50001"]
            initialDelaySeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  clusterIP: None
  selector:
    app: backend
  ports:
    - name: grpc
      port: 8080
      targetPort: 8080
      protocol: TCP